spring:
  application:
    name : activityservice
  data:
    mongodb:
      uri: mongodb://localhost:27017/aiactivityfitness
      database : aiactivityfitness
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
server:
  port: 8082
