spring:
  application:
    name: userservice
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness-micro-user
    username: abhyudayakandwal
    password:

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

server:
  port: 8081

